KIVINEN_EXPECT = [
	["/", ""],
	["/ ____file_type", "BIC"],
	["/ ____file_version", "V3.2"],
	["/ ____struct_type", 4294967295],
	["/Age", 18],
	["/Age. ____type", 5],
	["/AmbientAnimState", 0],
	["/AmbientAnimState. ____type", 0],
	["/AnimationDay", 461132],
	["/AnimationDay. ____type", 4],
	["/AnimationTime", 1629372],
	["/AnimationTime. ____type", 4],
	["/Appearance_Head", 1],
	["/Appearance_Head. ____type", 0],
	["/Appearance_Type", 6],
	["/Appearance_Type. ____type", 2],
	["/AreaId", 1],
	["/AreaId. ____type", 4],
	["/ArmorClass", 12],
	["/ArmorClass. ____type", 3],
	["/ArmorPart_RFoot", 1],
	["/ArmorPart_RFoot. ____type", 0],
	["/BaseAttackBonus", 1],
	["/BaseAttackBonus. ____type", 0],
	["/BodyBag", 0],
	["/BodyBag. ____type", 0],
	["/BodyBagId", 2130706432],
	["/BodyBagId. ____type", 4],
	["/BodyPart_Belt", 0],
	["/BodyPart_Belt. ____type", 0],
	["/BodyPart_LBicep", 1],
	["/BodyPart_LBicep. ____type", 0],
	["/BodyPart_LFArm", 1],
	["/BodyPart_LFArm. ____type", 0],
	["/BodyPart_LFoot", 1],
	["/BodyPart_LFoot. ____type", 0],
	["/BodyPart_LHand", 1],
	["/BodyPart_LHand. ____type", 0],
	["/BodyPart_LShin", 1],
	["/BodyPart_LShin. ____type", 0],
	["/BodyPart_LShoul", 0],
	["/BodyPart_LShoul. ____type", 0],
	["/BodyPart_LThigh", 1],
	["/BodyPart_LThigh. ____type", 0],
	["/BodyPart_Neck", 1],
	["/BodyPart_Neck. ____type", 0],
	["/BodyPart_Pelvis", 1],
	["/BodyPart_Pelvis. ____type", 0],
	["/BodyPart_RBicep", 1],
	["/BodyPart_RBicep. ____type", 0],
	["/BodyPart_RFArm", 1],
	["/BodyPart_RFArm. ____type", 0],
	["/BodyPart_RHand", 1],
	["/BodyPart_RHand. ____type", 0],
	["/BodyPart_RShin", 1],
	["/BodyPart_RShin. ____type", 0],
	["/BodyPart_RShoul", 0],
	["/BodyPart_RShoul. ____type", 0],
	["/BodyPart_RThigh", 1],
	["/BodyPart_RThigh. ____type", 0],
	["/BodyPart_Torso", 1],
	["/BodyPart_Torso. ____type", 0],
	["/Cha", 10],
	["/Cha. ____type", 0],
	["/ChallengeRating", 0.0],
	["/ChallengeRating. ____type", 8],
	["/ClassList. ____type", 15],
	["/ClassList[0]/", "/ClassList[0]"],
	["/ClassList[0]/ ____struct_type", 2],
	["/ClassList[0]/Class", 0],
	["/ClassList[0]/Class. ____type", 5],
	["/ClassList[0]/ClassLevel", 1],
	["/ClassList[0]/ClassLevel. ____type", 3],
	["/Color_Hair", 0],
	["/Color_Hair. ____type", 0],
	["/Color_Skin", 0],
	["/Color_Skin. ____type", 0],
	["/Color_Tattoo1", 0],
	["/Color_Tattoo1. ____type", 0],
	["/Color_Tattoo2", 0],
	["/Color_Tattoo2. ____type", 0],
	["/CombatInfo/", "/CombatInfo"],
	["/CombatInfo/ ____struct_type", 51882],
	["/CombatInfo. ____type", 14],
	["/CombatInfo/ArcaneSpellFail", 0],
	["/CombatInfo/ArcaneSpellFail. ____type", 0],
	["/CombatInfo/ArmorCheckPen", 0],
	["/CombatInfo/ArmorCheckPen. ____type", 0],
	["/CombatInfo/AttackList. ____type", 15],
	["/CombatInfo/CreatureDice", 0],
	["/CombatInfo/CreatureDice. ____type", 0],
	["/CombatInfo/CreatureDie", 0],
	["/CombatInfo/CreatureDie. ____type", 0],
	["/CombatInfo/DamageDice", 1],
	["/CombatInfo/DamageDice. ____type", 0],
	["/CombatInfo/DamageDie", 0],
	["/CombatInfo/DamageDie. ____type", 0],
	["/CombatInfo/DamageList. ____type", 15],
	["/CombatInfo/LeftEquip", 2130706432],
	["/CombatInfo/LeftEquip. ____type", 4],
	["/CombatInfo/LeftString", ""],
	["/CombatInfo/LeftString. ____type", 10],
	["/CombatInfo/NumAttacks", 1],
	["/CombatInfo/NumAttacks. ____type", 0],
	["/CombatInfo/OffHandAttackMod", 0],
	["/CombatInfo/OffHandAttackMod. ____type", 1],
	["/CombatInfo/OffHandCritMult", 2],
	["/CombatInfo/OffHandCritMult. ____type", 0],
	["/CombatInfo/OffHandCritRng", 1],
	["/CombatInfo/OffHandCritRng. ____type", 0],
	["/CombatInfo/OffHandDamageMod", 0],
	["/CombatInfo/OffHandDamageMod. ____type", 1],
	["/CombatInfo/OffHandWeaponEq", 0],
	["/CombatInfo/OffHandWeaponEq. ____type", 0],
	["/CombatInfo/OnHandAttackMod", 3],
	["/CombatInfo/OnHandAttackMod. ____type", 1],
	["/CombatInfo/OnHandCritMult", 3],
	["/CombatInfo/OnHandCritMult. ____type", 0],
	["/CombatInfo/OnHandCritRng", 1],
	["/CombatInfo/OnHandCritRng. ____type", 0],
	["/CombatInfo/OnHandDamageMod", 3],
	["/CombatInfo/OnHandDamageMod. ____type", 1],
	["/CombatInfo/RightEquip", 184],
	["/CombatInfo/RightEquip. ____type", 4],
	["/CombatInfo/RightString", "Lance"],
	["/CombatInfo/RightString. ____type", 10],
	["/CombatInfo/SpellResistance", 0],
	["/CombatInfo/SpellResistance. ____type", 0],
	["/CombatInfo/UnarmedDamDice", 1],
	["/CombatInfo/UnarmedDamDice. ____type", 0],
	["/CombatInfo/UnarmedDamDie", 3],
	["/CombatInfo/UnarmedDamDie. ____type", 0],
	["/CombatInfo/eatureDice", 0],
	["/CombatInfo/eatureDice. ____type", 0],
	["/CombatInfo/eatureDie", 0],
	["/CombatInfo/eatureDie. ____type", 0],
	["/CombatInfo/reatureDice", 0],
	["/CombatInfo/reatureDice. ____type", 0],
	["/CombatInfo/reatureDie", 0],
	["/CombatInfo/reatureDie. ____type", 0],
	["/CombatRoundData/", "/CombatRoundData"],
	["/CombatRoundData/ ____struct_type", 51930],
	["/CombatRoundData. ____type", 14],
	["/Con", 14],
	["/Con. ____type", 0],
	["/Conversation", ""],
	["/Conversation. ____type", 11],
	["/CreatnScrptFird", 1],
	["/CreatnScrptFird. ____type", 0],
	["/CreatureSize", 3],
	["/CreatureSize. ____type", 5],
	["/CurrentHitPoints", 12],
	["/CurrentHitPoints. ____type", 3],
	["/DeadSelectable", 1],
	["/DeadSelectable. ____type", 0],
	["/DecayTime", 5000],
	["/DecayTime. ____type", 4],
	["/Deity", ""],
	["/Deity. ____type", 10],
	["/Description. ____string_ref", 4294967295],
	["/Description. ____type", 12],
	["/Description/0", "Your only hope for fame and fortune, and to escape the life of a commoner, was to become an adventurer. Guided by your goals and dreams, you have set off in search of excitement."],
	["/DescriptionOverr", ""],
	["/DescriptionOverr. ____type", 10],
	["/DetectMode", 0],
	["/DetectMode. ____type", 0],
	["/Dex", 15],
	["/Dex. ____type", 0],
	["/Disarmable", 1],
	["/Disarmable. ____type", 0],
	["/EncounterObject", 2130706432],
	["/EncounterObject. ____type", 4],
	["/Equip_ItemList. ____type", 15],
	["/Equip_ItemList[0]/", "/Equip_ItemList[0]"],
	["/Equip_ItemList[0]/ ____struct_type", 2],
	["/Equip_ItemList[0]/AddCost", 0],
	["/Equip_ItemList[0]/AddCost. ____type", 4],
	["/Equip_ItemList[0]/ArmorPart_Belt", 0],
	["/Equip_ItemList[0]/ArmorPart_Belt. ____type", 0],
	["/Equip_ItemList[0]/ArmorPart_LBicep", 1],
	["/Equip_ItemList[0]/ArmorPart_LBicep. ____type", 0],
	["/Equip_ItemList[0]/ArmorPart_LFArm", 1],
	["/Equip_ItemList[0]/ArmorPart_LFArm. ____type", 0],
	["/Equip_ItemList[0]/ArmorPart_LFoot", 6],
	["/Equip_ItemList[0]/ArmorPart_LFoot. ____type", 0],
	["/Equip_ItemList[0]/ArmorPart_LHand", 1],
	["/Equip_ItemList[0]/ArmorPart_LHand. ____type", 0],
	["/Equip_ItemList[0]/ArmorPart_LShin", 16],
	["/Equip_ItemList[0]/ArmorPart_LShin. ____type", 0],
	["/Equip_ItemList[0]/ArmorPart_LShoul", 0],
	["/Equip_ItemList[0]/ArmorPart_LShoul. ____type", 0],
	["/Equip_ItemList[0]/ArmorPart_LThigh", 4],
	["/Equip_ItemList[0]/ArmorPart_LThigh. ____type", 0],
	["/Equip_ItemList[0]/ArmorPart_Neck", 1],
	["/Equip_ItemList[0]/ArmorPart_Neck. ____type", 0],
	["/Equip_ItemList[0]/ArmorPart_Pelvis", 17],
	["/Equip_ItemList[0]/ArmorPart_Pelvis. ____type", 0],
	["/Equip_ItemList[0]/ArmorPart_RBicep", 1],
	["/Equip_ItemList[0]/ArmorPart_RBicep. ____type", 0],
	["/Equip_ItemList[0]/ArmorPart_RFArm", 1],
	["/Equip_ItemList[0]/ArmorPart_RFArm. ____type", 0],
	["/Equip_ItemList[0]/ArmorPart_RFoot", 6],
	["/Equip_ItemList[0]/ArmorPart_RFoot. ____type", 0],
	["/Equip_ItemList[0]/ArmorPart_RHand", 1],
	["/Equip_ItemList[0]/ArmorPart_RHand. ____type", 0],
	["/Equip_ItemList[0]/ArmorPart_RShin", 16],
	["/Equip_ItemList[0]/ArmorPart_RShin. ____type", 0],
	["/Equip_ItemList[0]/ArmorPart_RShoul", 0],
	["/Equip_ItemList[0]/ArmorPart_RShoul. ____type", 0],
	["/Equip_ItemList[0]/ArmorPart_RThigh", 4],
	["/Equip_ItemList[0]/ArmorPart_RThigh. ____type", 0],
	["/Equip_ItemList[0]/ArmorPart_Robe", 0],
	["/Equip_ItemList[0]/ArmorPart_Robe. ____type", 0],
	["/Equip_ItemList[0]/ArmorPart_Torso", 50],
	["/Equip_ItemList[0]/ArmorPart_Torso. ____type", 0],
	["/Equip_ItemList[0]/BaseItem", 16],
	["/Equip_ItemList[0]/BaseItem. ____type", 5],
	["/Equip_ItemList[0]/Charges", 0],
	["/Equip_ItemList[0]/Charges. ____type", 0],
	["/Equip_ItemList[0]/Cloth1Color", 11],
	["/Equip_ItemList[0]/Cloth1Color. ____type", 0],
	["/Equip_ItemList[0]/Cloth2Color", 3],
	["/Equip_ItemList[0]/Cloth2Color. ____type", 0],
	["/Equip_ItemList[0]/Cost", 1],
	["/Equip_ItemList[0]/Cost. ____type", 4],
	["/Equip_ItemList[0]/Cursed", 0],
	["/Equip_ItemList[0]/Cursed. ____type", 0],
	["/Equip_ItemList[0]/DescIdentified. ____string_ref", 4294967295],
	["/Equip_ItemList[0]/DescIdentified. ____type", 12],
	["/Equip_ItemList[0]/DescIdentifiedOv", ""],
	["/Equip_ItemList[0]/DescIdentifiedOv. ____type", 10],
	["/Equip_ItemList[0]/Description. ____string_ref", 4294967295],
	["/Equip_ItemList[0]/Description. ____type", 12],
	["/Equip_ItemList[0]/DescriptionOverr", ""],
	["/Equip_ItemList[0]/DescriptionOverr. ____type", 10],
	["/Equip_ItemList[0]/Dropable", 1],
	["/Equip_ItemList[0]/Dropable. ____type", 0],
	["/Equip_ItemList[0]/Identified", 1],
	["/Equip_ItemList[0]/Identified. ____type", 0],
	["/Equip_ItemList[0]/Leather1Color", 11],
	["/Equip_ItemList[0]/Leather1Color. ____type", 0],
	["/Equip_ItemList[0]/Leather2Color", 15],
	["/Equip_ItemList[0]/Leather2Color. ____type", 0],
	["/Equip_ItemList[0]/LocalizedName. ____string_ref", 12902],
	["/Equip_ItemList[0]/LocalizedName. ____type", 12],
	["/Equip_ItemList[0]/Metal1Color", 2],
	["/Equip_ItemList[0]/Metal1Color. ____type", 0],
	["/Equip_ItemList[0]/Metal2Color", 11],
	["/Equip_ItemList[0]/Metal2Color. ____type", 0],
	["/Equip_ItemList[0]/ObjectId", 585],
	["/Equip_ItemList[0]/ObjectId. ____type", 4],
	["/Equip_ItemList[0]/Pickpocketable", 1],
	["/Equip_ItemList[0]/Pickpocketable. ____type", 0],
	["/Equip_ItemList[0]/Plot", 0],
	["/Equip_ItemList[0]/Plot. ____type", 0],
	["/Equip_ItemList[0]/PropertiesList. ____type", 15],
	["/Equip_ItemList[0]/StackSize", 1],
	["/Equip_ItemList[0]/StackSize. ____type", 2],
	["/Equip_ItemList[0]/Stolen", 0],
	["/Equip_ItemList[0]/Stolen. ____type", 0],
	["/Equip_ItemList[0]/Tag", "NW_CLOTH001"],
	["/Equip_ItemList[0]/Tag. ____type", 10],
	["/Equip_ItemList[0]/TemplateResRef", "nw_cloth001"],
	["/Equip_ItemList[0]/TemplateResRef. ____type", 11],
	["/Equip_ItemList[0]/UArmorPart_Belt", 0],
	["/Equip_ItemList[0]/UArmorPart_Belt. ____type", 0],
	["/Equip_ItemList[0]/UArmorPart_LBice", 1],
	["/Equip_ItemList[0]/UArmorPart_LBice. ____type", 0],
	["/Equip_ItemList[0]/UArmorPart_LFArm", 1],
	["/Equip_ItemList[0]/UArmorPart_LFArm. ____type", 0],
	["/Equip_ItemList[0]/UArmorPart_LFoot", 6],
	["/Equip_ItemList[0]/UArmorPart_LFoot. ____type", 0],
	["/Equip_ItemList[0]/UArmorPart_LHand", 1],
	["/Equip_ItemList[0]/UArmorPart_LHand. ____type", 0],
	["/Equip_ItemList[0]/UArmorPart_LShin", 16],
	["/Equip_ItemList[0]/UArmorPart_LShin. ____type", 0],
	["/Equip_ItemList[0]/UArmorPart_LShou", 0],
	["/Equip_ItemList[0]/UArmorPart_LShou. ____type", 0],
	["/Equip_ItemList[0]/UArmorPart_LThig", 4],
	["/Equip_ItemList[0]/UArmorPart_LThig. ____type", 0],
	["/Equip_ItemList[0]/UArmorPart_Neck", 1],
	["/Equip_ItemList[0]/UArmorPart_Neck. ____type", 0],
	["/Equip_ItemList[0]/UArmorPart_Pelvi", 17],
	["/Equip_ItemList[0]/UArmorPart_Pelvi. ____type", 0],
	["/Equip_ItemList[0]/UArmorPart_RBice", 1],
	["/Equip_ItemList[0]/UArmorPart_RBice. ____type", 0],
	["/Equip_ItemList[0]/UArmorPart_RFArm", 1],
	["/Equip_ItemList[0]/UArmorPart_RFArm. ____type", 0],
	["/Equip_ItemList[0]/UArmorPart_RFoot", 6],
	["/Equip_ItemList[0]/UArmorPart_RFoot. ____type", 0],
	["/Equip_ItemList[0]/UArmorPart_RHand", 1],
	["/Equip_ItemList[0]/UArmorPart_RHand. ____type", 0],
	["/Equip_ItemList[0]/UArmorPart_RShin", 16],
	["/Equip_ItemList[0]/UArmorPart_RShin. ____type", 0],
	["/Equip_ItemList[0]/UArmorPart_RShou", 0],
	["/Equip_ItemList[0]/UArmorPart_RShou. ____type", 0],
	["/Equip_ItemList[0]/UArmorPart_RThig", 4],
	["/Equip_ItemList[0]/UArmorPart_RThig. ____type", 0],
	["/Equip_ItemList[0]/UArmorPart_Robe", 0],
	["/Equip_ItemList[0]/UArmorPart_Robe. ____type", 0],
	["/Equip_ItemList[0]/UArmorPart_Torso", 50],
	["/Equip_ItemList[0]/UArmorPart_Torso. ____type", 0],
	["/Equip_ItemList[0]/XOrientation", 1.0],
	["/Equip_ItemList[0]/XOrientation. ____type", 8],
	["/Equip_ItemList[0]/XPosition", 0.0],
	["/Equip_ItemList[0]/XPosition. ____type", 8],
	["/Equip_ItemList[0]/YOrientation", 0.0],
	["/Equip_ItemList[0]/YOrientation. ____type", 8],
	["/Equip_ItemList[0]/YPosition", 0.0],
	["/Equip_ItemList[0]/YPosition. ____type", 8],
	["/Equip_ItemList[0]/ZOrientation", 0.0],
	["/Equip_ItemList[0]/ZOrientation. ____type", 8],
	["/Equip_ItemList[0]/ZPosition", 0.0],
	["/Equip_ItemList[0]/ZPosition. ____type", 8],
	["/Equip_ItemList[1]/", "/Equip_ItemList[1]"],
	["/Equip_ItemList[1]/ ____struct_type", 16],
	["/Equip_ItemList[1]/AddCost", 0],
	["/Equip_ItemList[1]/AddCost. ____type", 4],
	["/Equip_ItemList[1]/BaseItem", 92],
	["/Equip_ItemList[1]/BaseItem. ____type", 5],
	["/Equip_ItemList[1]/Charges", 0],
	["/Equip_ItemList[1]/Charges. ____type", 0],
	["/Equip_ItemList[1]/Cost", 2],
	["/Equip_ItemList[1]/Cost. ____type", 4],
	["/Equip_ItemList[1]/Cursed", 0],
	["/Equip_ItemList[1]/Cursed. ____type", 0],
	["/Equip_ItemList[1]/DescIdentified. ____string_ref", 4294967295],
	["/Equip_ItemList[1]/DescIdentified. ____type", 12],
	["/Equip_ItemList[1]/DescIdentifiedOv", ""],
	["/Equip_ItemList[1]/DescIdentifiedOv. ____type", 10],
	["/Equip_ItemList[1]/Description. ____string_ref", 4294967295],
	["/Equip_ItemList[1]/Description. ____type", 12],
	["/Equip_ItemList[1]/DescriptionOverr", ""],
	["/Equip_ItemList[1]/DescriptionOverr. ____type", 10],
	["/Equip_ItemList[1]/Dropable", 1],
	["/Equip_ItemList[1]/Dropable. ____type", 0],
	["/Equip_ItemList[1]/Identified", 1],
	["/Equip_ItemList[1]/Identified. ____type", 0],
	["/Equip_ItemList[1]/LocalizedName. ____string_ref", 4294967295],
	["/Equip_ItemList[1]/LocalizedName. ____type", 12],
	["/Equip_ItemList[1]/LocalizedName/0", "Lance"],
	["/Equip_ItemList[1]/ModelPart1", 12],
	["/Equip_ItemList[1]/ModelPart1. ____type", 0],
	["/Equip_ItemList[1]/ModelPart2", 11],
	["/Equip_ItemList[1]/ModelPart2. ____type", 0],
	["/Equip_ItemList[1]/ModelPart3", 11],
	["/Equip_ItemList[1]/ModelPart3. ____type", 0],
	["/Equip_ItemList[1]/ObjectId", 184],
	["/Equip_ItemList[1]/ObjectId. ____type", 4],
	["/Equip_ItemList[1]/Pickpocketable", 1],
	["/Equip_ItemList[1]/Pickpocketable. ____type", 0],
	["/Equip_ItemList[1]/Plot", 0],
	["/Equip_ItemList[1]/Plot. ____type", 0],
	["/Equip_ItemList[1]/PropertiesList. ____type", 15],
	["/Equip_ItemList[1]/StackSize", 1],
	["/Equip_ItemList[1]/StackSize. ____type", 2],
	["/Equip_ItemList[1]/Stolen", 0],
	["/Equip_ItemList[1]/Stolen. ____type", 0],
	["/Equip_ItemList[1]/Tag", "Lance"],
	["/Equip_ItemList[1]/Tag. ____type", 10],
	["/Equip_ItemList[1]/TemplateResRef", "lance"],
	["/Equip_ItemList[1]/TemplateResRef. ____type", 11],
	["/Equip_ItemList[1]/XOrientation", 0.0],
	["/Equip_ItemList[1]/XOrientation. ____type", 8],
	["/Equip_ItemList[1]/XPosition", 0.0],
	["/Equip_ItemList[1]/XPosition. ____type", 8],
	["/Equip_ItemList[1]/YOrientation", 1.0],
	["/Equip_ItemList[1]/YOrientation. ____type", 8],
	["/Equip_ItemList[1]/YPosition", 0.0],
	["/Equip_ItemList[1]/YPosition. ____type", 8],
	["/Equip_ItemList[1]/ZOrientation", 0.0],
	["/Equip_ItemList[1]/ZOrientation. ____type", 8],
	["/Equip_ItemList[1]/ZPosition", 0.0],
	["/Equip_ItemList[1]/ZPosition. ____type", 8],
	["/Equip_ItemList[2]/", "/Equip_ItemList[2]"],
	["/Equip_ItemList[2]/ ____struct_type", 131072],
	["/Equip_ItemList[2]/AddCost", 0],
	["/Equip_ItemList[2]/AddCost. ____type", 4],
	["/Equip_ItemList[2]/BaseItem", 73],
	["/Equip_ItemList[2]/BaseItem. ____type", 5],
	["/Equip_ItemList[2]/Charges", 0],
	["/Equip_ItemList[2]/Charges. ____type", 0],
	["/Equip_ItemList[2]/Cost", 0],
	["/Equip_ItemList[2]/Cost. ____type", 4],
	["/Equip_ItemList[2]/Cursed", 1],
	["/Equip_ItemList[2]/Cursed. ____type", 0],
	["/Equip_ItemList[2]/DescIdentified. ____string_ref", 4294967295],
	["/Equip_ItemList[2]/DescIdentified. ____type", 12],
	["/Equip_ItemList[2]/DescIdentified/0", "This item is used for Expansion Pack 3 (1.69) to store PC properties used by horse scripts."],
	["/Equip_ItemList[2]/DescIdentifiedOv", ""],
	["/Equip_ItemList[2]/DescIdentifiedOv. ____type", 10],
	["/Equip_ItemList[2]/Description. ____string_ref", 4294967295],
	["/Equip_ItemList[2]/Description. ____type", 12],
	["/Equip_ItemList[2]/Description/0", ""],
	["/Equip_ItemList[2]/DescriptionOverr", ""],
	["/Equip_ItemList[2]/DescriptionOverr. ____type", 10],
	["/Equip_ItemList[2]/Dropable", 0],
	["/Equip_ItemList[2]/Dropable. ____type", 0],
	["/Equip_ItemList[2]/Identified", 1],
	["/Equip_ItemList[2]/Identified. ____type", 0],
	["/Equip_ItemList[2]/LocalizedName. ____string_ref", 4294967295],
	["/Equip_ItemList[2]/LocalizedName. ____type", 12],
	["/Equip_ItemList[2]/LocalizedName/0", "PC Properties"],
	["/Equip_ItemList[2]/ModelPart1", 1],
	["/Equip_ItemList[2]/ModelPart1. ____type", 0],
	["/Equip_ItemList[2]/ObjectId", 592],
	["/Equip_ItemList[2]/ObjectId. ____type", 4],
	["/Equip_ItemList[2]/Pickpocketable", 0],
	["/Equip_ItemList[2]/Pickpocketable. ____type", 0],
	["/Equip_ItemList[2]/Plot", 1],
	["/Equip_ItemList[2]/Plot. ____type", 0],
	["/Equip_ItemList[2]/PropertiesList. ____type", 15],
	["/Equip_ItemList[2]/StackSize", 1],
	["/Equip_ItemList[2]/StackSize. ____type", 2],
	["/Equip_ItemList[2]/Stolen", 0],
	["/Equip_ItemList[2]/Stolen. ____type", 0],
	["/Equip_ItemList[2]/Tag", "x3_it_pchide"],
	["/Equip_ItemList[2]/Tag. ____type", 10],
	["/Equip_ItemList[2]/TemplateResRef", "x3_it_pchide"],
	["/Equip_ItemList[2]/TemplateResRef. ____type", 11],
	["/Equip_ItemList[2]/XOrientation", 1.0],
	["/Equip_ItemList[2]/XOrientation. ____type", 8],
	["/Equip_ItemList[2]/XPosition", 0.0],
	["/Equip_ItemList[2]/XPosition. ____type", 8],
	["/Equip_ItemList[2]/YOrientation", 0.0],
	["/Equip_ItemList[2]/YOrientation. ____type", 8],
	["/Equip_ItemList[2]/YPosition", 0.0],
	["/Equip_ItemList[2]/YPosition. ____type", 8],
	["/Equip_ItemList[2]/ZOrientation", 0.0],
	["/Equip_ItemList[2]/ZOrientation. ____type", 8],
	["/Equip_ItemList[2]/ZPosition", 0.0],
	["/Equip_ItemList[2]/ZPosition. ____type", 8],
	["/Experience", 0],
	["/Experience. ____type", 4],
	["/FactionID", 5],
	["/FactionID. ____type", 2],
	["/FeatList. ____type", 15],
	["/FeatList[0]/", "/FeatList[0]"],
	["/FeatList[0]/ ____struct_type", 1],
	["/FeatList[0]/Feat", 3],
	["/FeatList[0]/Feat. ____type", 2],
	["/FeatList[1]/", "/FeatList[1]"],
	["/FeatList[1]/ ____struct_type", 1],
	["/FeatList[1]/Feat", 4],
	["/FeatList[1]/Feat. ____type", 2],
	["/FeatList[2]/", "/FeatList[2]"],
	["/FeatList[2]/ ____struct_type", 1],
	["/FeatList[2]/Feat", 32],
	["/FeatList[2]/Feat. ____type", 2],
	["/FeatList[3]/", "/FeatList[3]"],
	["/FeatList[3]/ ____struct_type", 1],
	["/FeatList[3]/Feat", 45],
	["/FeatList[3]/Feat. ____type", 2],
	["/FeatList[4]/", "/FeatList[4]"],
	["/FeatList[4]/ ____struct_type", 1],
	["/FeatList[4]/Feat", 46],
	["/FeatList[4]/Feat. ____type", 2],
	["/FeatList[5]/", "/FeatList[5]"],
	["/FeatList[5]/ ____struct_type", 1],
	["/FeatList[5]/Feat", 194],
	["/FeatList[5]/Feat. ____type", 2],
	["/FeatList[6]/", "/FeatList[6]"],
	["/FeatList[6]/ ____struct_type", 1],
	["/FeatList[6]/Feat", 258],
	["/FeatList[6]/Feat. ____type", 2],
	["/FeatList[7]/", "/FeatList[7]"],
	["/FeatList[7]/ ____struct_type", 1],
	["/FeatList[7]/Feat", 293],
	["/FeatList[7]/Feat. ____type", 2],
	["/FeatList[7]/Uses", 1],
	["/FeatList[7]/Uses. ____type", 0],
	["/FeatList[8]/", "/FeatList[8]"],
	["/FeatList[8]/ ____struct_type", 1],
	["/FeatList[8]/Feat", 1089],
	["/FeatList[8]/Feat. ____type", 2],
	["/FeatList[9]/", "/FeatList[9]"],
	["/FeatList[9]/ ____struct_type", 1],
	["/FeatList[9]/Feat", 28],
	["/FeatList[9]/Feat. ____type", 2],
	["/FeatList[10]/", "/FeatList[10]"],
	["/FeatList[10]/ ____struct_type", 1],
	["/FeatList[10]/Feat", 111],
	["/FeatList[10]/Feat. ____type", 2],
	["/FirstName. ____string_ref", 4294967295],
	["/FirstName. ____type", 12],
	["/FirstName/0", "Test"],
	["/FootstepType", -1],
	["/FootstepType. ____type", 5],
	["/FortSaveThrow", 4],
	["/FortSaveThrow. ____type", 1],
	["/Gender", 0],
	["/Gender. ____type", 0],
	["/Gold", 20],
	["/Gold. ____type", 4],
	["/GoodEvil", 50],
	["/GoodEvil. ____type", 0],
	["/HitPoints", 12],
	["/HitPoints. ____type", 3],
	["/Int", 10],
	["/Int. ____type", 0],
	["/Interruptable", 1],
	["/Interruptable. ____type", 0],
	["/IsCommandable", 1],
	["/IsCommandable. ____type", 0],
	["/IsDM", 0],
	["/IsDM. ____type", 0],
	["/IsDestroyable", 1],
	["/IsDestroyable. ____type", 0],
	["/IsImmortal", 0],
	["/IsImmortal. ____type", 0],
	["/IsPC", 1],
	["/IsPC. ____type", 0],
	["/IsRaiseable", 1],
	["/IsRaiseable. ____type", 0],
	["/ItemList. ____type", 15],
	["/ItemList[0]/", "/ItemList[0]"],
	["/ItemList[0]/ ____struct_type", 0],
	["/ItemList[0]/AddCost", 0],
	["/ItemList[0]/AddCost. ____type", 4],
	["/ItemList[0]/BaseItem", 49],
	["/ItemList[0]/BaseItem. ____type", 5],
	["/ItemList[0]/Charges", 0],
	["/ItemList[0]/Charges. ____type", 0],
	["/ItemList[0]/Cost", 20],
	["/ItemList[0]/Cost. ____type", 4],
	["/ItemList[0]/Cursed", 0],
	["/ItemList[0]/Cursed. ____type", 0],
	["/ItemList[0]/DescIdentified. ____string_ref", 13410],
	["/ItemList[0]/DescIdentified. ____type", 12],
	["/ItemList[0]/DescIdentifiedOv", ""],
	["/ItemList[0]/DescIdentifiedOv. ____type", 10],
	["/ItemList[0]/Description. ____string_ref", 4294967295],
	["/ItemList[0]/Description. ____type", 12],
	["/ItemList[0]/DescriptionOverr", ""],
	["/ItemList[0]/DescriptionOverr. ____type", 10],
	["/ItemList[0]/Dropable", 1],
	["/ItemList[0]/Dropable. ____type", 0],
	["/ItemList[0]/Identified", 1],
	["/ItemList[0]/Identified. ____type", 0],
	["/ItemList[0]/LocalizedName. ____string_ref", 13411],
	["/ItemList[0]/LocalizedName. ____type", 12],
	["/ItemList[0]/ModelPart1", 21],
	["/ItemList[0]/ModelPart1. ____type", 0],
	["/ItemList[0]/ModelPart2", 23],
	["/ItemList[0]/ModelPart2. ____type", 0],
	["/ItemList[0]/ModelPart3", 32],
	["/ItemList[0]/ModelPart3. ____type", 0],
	["/ItemList[0]/ObjectId", 591],
	["/ItemList[0]/ObjectId. ____type", 4],
	["/ItemList[0]/Pickpocketable", 1],
	["/ItemList[0]/Pickpocketable. ____type", 0],
	["/ItemList[0]/Plot", 0],
	["/ItemList[0]/Plot. ____type", 0],
	["/ItemList[0]/PropertiesList. ____type", 15],
	["/ItemList[0]/PropertiesList[0]/", "/ItemList[0]/PropertiesList[0]"],
	["/ItemList[0]/PropertiesList[0]/ ____struct_type", 0],
	["/ItemList[0]/PropertiesList[0]/ChanceAppear", 100],
	["/ItemList[0]/PropertiesList[0]/ChanceAppear. ____type", 0],
	["/ItemList[0]/PropertiesList[0]/CostTable", 3],
	["/ItemList[0]/PropertiesList[0]/CostTable. ____type", 0],
	["/ItemList[0]/PropertiesList[0]/CostValue", 1],
	["/ItemList[0]/PropertiesList[0]/CostValue. ____type", 2],
	["/ItemList[0]/PropertiesList[0]/Param1", 255],
	["/ItemList[0]/PropertiesList[0]/Param1. ____type", 0],
	["/ItemList[0]/PropertiesList[0]/Param1Value", 255],
	["/ItemList[0]/PropertiesList[0]/Param1Value. ____type", 0],
	["/ItemList[0]/PropertiesList[0]/PropertyName", 15],
	["/ItemList[0]/PropertiesList[0]/PropertyName. ____type", 2],
	["/ItemList[0]/PropertiesList[0]/Subtype", 66],
	["/ItemList[0]/PropertiesList[0]/Subtype. ____type", 2],
	["/ItemList[0]/PropertiesList[0]/Useable", 1],
	["/ItemList[0]/PropertiesList[0]/Useable. ____type", 0],
	["/ItemList[0]/PropertiesList[0]/UsesPerDay", 255],
	["/ItemList[0]/PropertiesList[0]/UsesPerDay. ____type", 0],
	["/ItemList[0]/Repos_PosX", 6],
	["/ItemList[0]/Repos_PosX. ____type", 2],
	["/ItemList[0]/Repos_Posy", 0],
	["/ItemList[0]/Repos_Posy. ____type", 2],
	["/ItemList[0]/StackSize", 1],
	["/ItemList[0]/StackSize. ____type", 2],
	["/ItemList[0]/Stolen", 0],
	["/ItemList[0]/Stolen. ____type", 0],
	["/ItemList[0]/Tag", "NW_IT_MPOTION001"],
	["/ItemList[0]/Tag. ____type", 10],
	["/ItemList[0]/TemplateResRef", "nw_it_mpotion001"],
	["/ItemList[0]/TemplateResRef. ____type", 11],
	["/ItemList[0]/XOrientation", 1.0],
	["/ItemList[0]/XOrientation. ____type", 8],
	["/ItemList[0]/XPosition", 0.0],
	["/ItemList[0]/XPosition. ____type", 8],
	["/ItemList[0]/YOrientation", 0.0],
	["/ItemList[0]/YOrientation. ____type", 8],
	["/ItemList[0]/YPosition", 0.0],
	["/ItemList[0]/YPosition. ____type", 8],
	["/ItemList[0]/ZOrientation", 0.0],
	["/ItemList[0]/ZOrientation. ____type", 8],
	["/ItemList[0]/ZPosition", 0.0],
	["/ItemList[0]/ZPosition. ____type", 8],
	["/ItemList[1]/", "/ItemList[1]"],
	["/ItemList[1]/ ____struct_type", 0],
	["/ItemList[1]/AddCost", 0],
	["/ItemList[1]/AddCost. ____type", 4],
	["/ItemList[1]/BaseItem", 49],
	["/ItemList[1]/BaseItem. ____type", 5],
	["/ItemList[1]/Charges", 0],
	["/ItemList[1]/Charges. ____type", 0],
	["/ItemList[1]/Cost", 20],
	["/ItemList[1]/Cost. ____type", 4],
	["/ItemList[1]/Cursed", 0],
	["/ItemList[1]/Cursed. ____type", 0],
	["/ItemList[1]/DescIdentified. ____string_ref", 13410],
	["/ItemList[1]/DescIdentified. ____type", 12],
	["/ItemList[1]/DescIdentifiedOv", ""],
	["/ItemList[1]/DescIdentifiedOv. ____type", 10],
	["/ItemList[1]/Description. ____string_ref", 4294967295],
	["/ItemList[1]/Description. ____type", 12],
	["/ItemList[1]/DescriptionOverr", ""],
	["/ItemList[1]/DescriptionOverr. ____type", 10],
	["/ItemList[1]/Dropable", 1],
	["/ItemList[1]/Dropable. ____type", 0],
	["/ItemList[1]/Identified", 1],
	["/ItemList[1]/Identified. ____type", 0],
	["/ItemList[1]/LocalizedName. ____string_ref", 13411],
	["/ItemList[1]/LocalizedName. ____type", 12],
	["/ItemList[1]/ModelPart1", 21],
	["/ItemList[1]/ModelPart1. ____type", 0],
	["/ItemList[1]/ModelPart2", 23],
	["/ItemList[1]/ModelPart2. ____type", 0],
	["/ItemList[1]/ModelPart3", 32],
	["/ItemList[1]/ModelPart3. ____type", 0],
	["/ItemList[1]/ObjectId", 590],
	["/ItemList[1]/ObjectId. ____type", 4],
	["/ItemList[1]/Pickpocketable", 1],
	["/ItemList[1]/Pickpocketable. ____type", 0],
	["/ItemList[1]/Plot", 0],
	["/ItemList[1]/Plot. ____type", 0],
	["/ItemList[1]/PropertiesList. ____type", 15],
	["/ItemList[1]/PropertiesList[0]/", "/ItemList[1]/PropertiesList[0]"],
	["/ItemList[1]/PropertiesList[0]/ ____struct_type", 0],
	["/ItemList[1]/PropertiesList[0]/ChanceAppear", 100],
	["/ItemList[1]/PropertiesList[0]/ChanceAppear. ____type", 0],
	["/ItemList[1]/PropertiesList[0]/CostTable", 3],
	["/ItemList[1]/PropertiesList[0]/CostTable. ____type", 0],
	["/ItemList[1]/PropertiesList[0]/CostValue", 1],
	["/ItemList[1]/PropertiesList[0]/CostValue. ____type", 2],
	["/ItemList[1]/PropertiesList[0]/Param1", 255],
	["/ItemList[1]/PropertiesList[0]/Param1. ____type", 0],
	["/ItemList[1]/PropertiesList[0]/Param1Value", 255],
	["/ItemList[1]/PropertiesList[0]/Param1Value. ____type", 0],
	["/ItemList[1]/PropertiesList[0]/PropertyName", 15],
	["/ItemList[1]/PropertiesList[0]/PropertyName. ____type", 2],
	["/ItemList[1]/PropertiesList[0]/Subtype", 66],
	["/ItemList[1]/PropertiesList[0]/Subtype. ____type", 2],
	["/ItemList[1]/PropertiesList[0]/Useable", 1],
	["/ItemList[1]/PropertiesList[0]/Useable. ____type", 0],
	["/ItemList[1]/PropertiesList[0]/UsesPerDay", 255],
	["/ItemList[1]/PropertiesList[0]/UsesPerDay. ____type", 0],
	["/ItemList[1]/Repos_PosX", 5],
	["/ItemList[1]/Repos_PosX. ____type", 2],
	["/ItemList[1]/Repos_Posy", 0],
	["/ItemList[1]/Repos_Posy. ____type", 2],
	["/ItemList[1]/StackSize", 1],
	["/ItemList[1]/StackSize. ____type", 2],
	["/ItemList[1]/Stolen", 0],
	["/ItemList[1]/Stolen. ____type", 0],
	["/ItemList[1]/Tag", "NW_IT_MPOTION001"],
	["/ItemList[1]/Tag. ____type", 10],
	["/ItemList[1]/TemplateResRef", "nw_it_mpotion001"],
	["/ItemList[1]/TemplateResRef. ____type", 11],
	["/ItemList[1]/XOrientation", 1.0],
	["/ItemList[1]/XOrientation. ____type", 8],
	["/ItemList[1]/XPosition", 0.0],
	["/ItemList[1]/XPosition. ____type", 8],
	["/ItemList[1]/YOrientation", 0.0],
	["/ItemList[1]/YOrientation. ____type", 8],
	["/ItemList[1]/YPosition", 0.0],
	["/ItemList[1]/YPosition. ____type", 8],
	["/ItemList[1]/ZOrientation", 0.0],
	["/ItemList[1]/ZOrientation. ____type", 8],
	["/ItemList[1]/ZPosition", 0.0],
	["/ItemList[1]/ZPosition. ____type", 8],
	["/ItemList[2]/", "/ItemList[2]"],
	["/ItemList[2]/ ____struct_type", 0],
	["/ItemList[2]/AddCost", 0],
	["/ItemList[2]/AddCost. ____type", 4],
	["/ItemList[2]/BaseItem", 49],
	["/ItemList[2]/BaseItem. ____type", 5],
	["/ItemList[2]/Charges", 0],
	["/ItemList[2]/Charges. ____type", 0],
	["/ItemList[2]/Cost", 20],
	["/ItemList[2]/Cost. ____type", 4],
	["/ItemList[2]/Cursed", 0],
	["/ItemList[2]/Cursed. ____type", 0],
	["/ItemList[2]/DescIdentified. ____string_ref", 13410],
	["/ItemList[2]/DescIdentified. ____type", 12],
	["/ItemList[2]/DescIdentifiedOv", ""],
	["/ItemList[2]/DescIdentifiedOv. ____type", 10],
	["/ItemList[2]/Description. ____string_ref", 4294967295],
	["/ItemList[2]/Description. ____type", 12],
	["/ItemList[2]/DescriptionOverr", ""],
	["/ItemList[2]/DescriptionOverr. ____type", 10],
	["/ItemList[2]/Dropable", 1],
	["/ItemList[2]/Dropable. ____type", 0],
	["/ItemList[2]/Identified", 1],
	["/ItemList[2]/Identified. ____type", 0],
	["/ItemList[2]/LocalizedName. ____string_ref", 13411],
	["/ItemList[2]/LocalizedName. ____type", 12],
	["/ItemList[2]/ModelPart1", 21],
	["/ItemList[2]/ModelPart1. ____type", 0],
	["/ItemList[2]/ModelPart2", 23],
	["/ItemList[2]/ModelPart2. ____type", 0],
	["/ItemList[2]/ModelPart3", 32],
	["/ItemList[2]/ModelPart3. ____type", 0],
	["/ItemList[2]/ObjectId", 589],
	["/ItemList[2]/ObjectId. ____type", 4],
	["/ItemList[2]/Pickpocketable", 1],
	["/ItemList[2]/Pickpocketable. ____type", 0],
	["/ItemList[2]/Plot", 0],
	["/ItemList[2]/Plot. ____type", 0],
	["/ItemList[2]/PropertiesList. ____type", 15],
	["/ItemList[2]/PropertiesList[0]/", "/ItemList[2]/PropertiesList[0]"],
	["/ItemList[2]/PropertiesList[0]/ ____struct_type", 0],
	["/ItemList[2]/PropertiesList[0]/ChanceAppear", 100],
	["/ItemList[2]/PropertiesList[0]/ChanceAppear. ____type", 0],
	["/ItemList[2]/PropertiesList[0]/CostTable", 3],
	["/ItemList[2]/PropertiesList[0]/CostTable. ____type", 0],
	["/ItemList[2]/PropertiesList[0]/CostValue", 1],
	["/ItemList[2]/PropertiesList[0]/CostValue. ____type", 2],
	["/ItemList[2]/PropertiesList[0]/Param1", 255],
	["/ItemList[2]/PropertiesList[0]/Param1. ____type", 0],
	["/ItemList[2]/PropertiesList[0]/Param1Value", 255],
	["/ItemList[2]/PropertiesList[0]/Param1Value. ____type", 0],
	["/ItemList[2]/PropertiesList[0]/PropertyName", 15],
	["/ItemList[2]/PropertiesList[0]/PropertyName. ____type", 2],
	["/ItemList[2]/PropertiesList[0]/Subtype", 66],
	["/ItemList[2]/PropertiesList[0]/Subtype. ____type", 2],
	["/ItemList[2]/PropertiesList[0]/Useable", 1],
	["/ItemList[2]/PropertiesList[0]/Useable. ____type", 0],
	["/ItemList[2]/PropertiesList[0]/UsesPerDay", 255],
	["/ItemList[2]/PropertiesList[0]/UsesPerDay. ____type", 0],
	["/ItemList[2]/Repos_PosX", 4],
	["/ItemList[2]/Repos_PosX. ____type", 2],
	["/ItemList[2]/Repos_Posy", 0],
	["/ItemList[2]/Repos_Posy. ____type", 2],
	["/ItemList[2]/StackSize", 1],
	["/ItemList[2]/StackSize. ____type", 2],
	["/ItemList[2]/Stolen", 0],
	["/ItemList[2]/Stolen. ____type", 0],
	["/ItemList[2]/Tag", "NW_IT_MPOTION001"],
	["/ItemList[2]/Tag. ____type", 10],
	["/ItemList[2]/TemplateResRef", "nw_it_mpotion001"],
	["/ItemList[2]/TemplateResRef. ____type", 11],
	["/ItemList[2]/XOrientation", 1.0],
	["/ItemList[2]/XOrientation. ____type", 8],
	["/ItemList[2]/XPosition", 0.0],
	["/ItemList[2]/XPosition. ____type", 8],
	["/ItemList[2]/YOrientation", 0.0],
	["/ItemList[2]/YOrientation. ____type", 8],
	["/ItemList[2]/YPosition", 0.0],
	["/ItemList[2]/YPosition. ____type", 8],
	["/ItemList[2]/ZOrientation", 0.0],
	["/ItemList[2]/ZOrientation. ____type", 8],
	["/ItemList[2]/ZPosition", 0.0],
	["/ItemList[2]/ZPosition. ____type", 8],
	["/ItemList[3]/", "/ItemList[3]"],
	["/ItemList[3]/ ____struct_type", 0],
	["/ItemList[3]/AddCost", 1],
	["/ItemList[3]/AddCost. ____type", 4],
	["/ItemList[3]/BaseItem", 15],
	["/ItemList[3]/BaseItem. ____type", 5],
	["/ItemList[3]/Charges", 0],
	["/ItemList[3]/Charges. ____type", 0],
	["/ItemList[3]/Cost", 6],
	["/ItemList[3]/Cost. ____type", 4],
	["/ItemList[3]/Cursed", 0],
	["/ItemList[3]/Cursed. ____type", 0],
	["/ItemList[3]/DescIdentified. ____string_ref", 4294967295],
	["/ItemList[3]/DescIdentified. ____type", 12],
	["/ItemList[3]/DescIdentifiedOv", ""],
	["/ItemList[3]/DescIdentifiedOv. ____type", 10],
	["/ItemList[3]/Description. ____string_ref", 4294967295],
	["/ItemList[3]/Description. ____type", 12],
	["/ItemList[3]/DescriptionOverr", ""],
	["/ItemList[3]/DescriptionOverr. ____type", 10],
	["/ItemList[3]/Dropable", 1],
	["/ItemList[3]/Dropable. ____type", 0],
	["/ItemList[3]/Identified", 1],
	["/ItemList[3]/Identified. ____type", 0],
	["/ItemList[3]/LocalizedName. ____string_ref", 180],
	["/ItemList[3]/LocalizedName. ____type", 12],
	["/ItemList[3]/ModelPart1", 0],
	["/ItemList[3]/ModelPart1. ____type", 0],
	["/ItemList[3]/ObjectId", 588],
	["/ItemList[3]/ObjectId. ____type", 4],
	["/ItemList[3]/Pickpocketable", 1],
	["/ItemList[3]/Pickpocketable. ____type", 0],
	["/ItemList[3]/Plot", 0],
	["/ItemList[3]/Plot. ____type", 0],
	["/ItemList[3]/PropertiesList. ____type", 15],
	["/ItemList[3]/PropertiesList[0]/", "/ItemList[3]/PropertiesList[0]"],
	["/ItemList[3]/PropertiesList[0]/ ____struct_type", 0],
	["/ItemList[3]/PropertiesList[0]/ChanceAppear", 100],
	["/ItemList[3]/PropertiesList[0]/ChanceAppear. ____type", 0],
	["/ItemList[3]/PropertiesList[0]/CostTable", 18],
	["/ItemList[3]/PropertiesList[0]/CostTable. ____type", 0],
	["/ItemList[3]/PropertiesList[0]/CostValue", 4],
	["/ItemList[3]/PropertiesList[0]/CostValue. ____type", 2],
	["/ItemList[3]/PropertiesList[0]/Param1", 9],
	["/ItemList[3]/PropertiesList[0]/Param1. ____type", 0],
	["/ItemList[3]/PropertiesList[0]/Param1Value", 1],
	["/ItemList[3]/PropertiesList[0]/Param1Value. ____type", 0],
	["/ItemList[3]/PropertiesList[0]/PropertyName", 44],
	["/ItemList[3]/PropertiesList[0]/PropertyName. ____type", 2],
	["/ItemList[3]/PropertiesList[0]/Subtype", 0],
	["/ItemList[3]/PropertiesList[0]/Subtype. ____type", 2],
	["/ItemList[3]/PropertiesList[0]/Useable", 1],
	["/ItemList[3]/PropertiesList[0]/Useable. ____type", 0],
	["/ItemList[3]/PropertiesList[0]/UsesPerDay", 255],
	["/ItemList[3]/PropertiesList[0]/UsesPerDay. ____type", 0],
	["/ItemList[3]/Repos_PosX", 3],
	["/ItemList[3]/Repos_PosX. ____type", 2],
	["/ItemList[3]/Repos_Posy", 0],
	["/ItemList[3]/Repos_Posy. ____type", 2],
	["/ItemList[3]/StackSize", 1],
	["/ItemList[3]/StackSize. ____type", 2],
	["/ItemList[3]/Stolen", 0],
	["/ItemList[3]/Stolen. ____type", 0],
	["/ItemList[3]/Tag", "NW_IT_TORCH001"],
	["/ItemList[3]/Tag. ____type", 10],
	["/ItemList[3]/TemplateResRef", "nw_it_torch001"],
	["/ItemList[3]/TemplateResRef. ____type", 11],
	["/ItemList[3]/XOrientation", 1.0],
	["/ItemList[3]/XOrientation. ____type", 8],
	["/ItemList[3]/XPosition", 0.0],
	["/ItemList[3]/XPosition. ____type", 8],
	["/ItemList[3]/YOrientation", 0.0],
	["/ItemList[3]/YOrientation. ____type", 8],
	["/ItemList[3]/YPosition", 0.0],
	["/ItemList[3]/YPosition. ____type", 8],
	["/ItemList[3]/ZOrientation", 0.0],
	["/ItemList[3]/ZOrientation. ____type", 8],
	["/ItemList[3]/ZPosition", 0.0],
	["/ItemList[3]/ZPosition. ____type", 8],
	["/ItemList[4]/", "/ItemList[4]"],
	["/ItemList[4]/ ____struct_type", 0],
	["/ItemList[4]/AddCost", 0],
	["/ItemList[4]/AddCost. ____type", 4],
	["/ItemList[4]/ArmorPart_Belt", 0],
	["/ItemList[4]/ArmorPart_Belt. ____type", 0],
	["/ItemList[4]/ArmorPart_LBicep", 4],
	["/ItemList[4]/ArmorPart_LBicep. ____type", 0],
	["/ItemList[4]/ArmorPart_LFArm", 16],
	["/ItemList[4]/ArmorPart_LFArm. ____type", 0],
	["/ItemList[4]/ArmorPart_LFoot", 4],
	["/ItemList[4]/ArmorPart_LFoot. ____type", 0],
	["/ItemList[4]/ArmorPart_LHand", 3],
	["/ItemList[4]/ArmorPart_LHand. ____type", 0],
	["/ItemList[4]/ArmorPart_LShin", 13],
	["/ItemList[4]/ArmorPart_LShin. ____type", 0],
	["/ItemList[4]/ArmorPart_LShoul", 15],
	["/ItemList[4]/ArmorPart_LShoul. ____type", 0],
	["/ItemList[4]/ArmorPart_LThigh", 3],
	["/ItemList[4]/ArmorPart_LThigh. ____type", 0],
	["/ItemList[4]/ArmorPart_Neck", 1],
	["/ItemList[4]/ArmorPart_Neck. ____type", 0],
	["/ItemList[4]/ArmorPart_Pelvis", 8],
	["/ItemList[4]/ArmorPart_Pelvis. ____type", 0],
	["/ItemList[4]/ArmorPart_RBicep", 4],
	["/ItemList[4]/ArmorPart_RBicep. ____type", 0],
	["/ItemList[4]/ArmorPart_RFArm", 16],
	["/ItemList[4]/ArmorPart_RFArm. ____type", 0],
	["/ItemList[4]/ArmorPart_RFoot", 4],
	["/ItemList[4]/ArmorPart_RFoot. ____type", 0],
	["/ItemList[4]/ArmorPart_RHand", 3],
	["/ItemList[4]/ArmorPart_RHand. ____type", 0],
	["/ItemList[4]/ArmorPart_RShin", 13],
	["/ItemList[4]/ArmorPart_RShin. ____type", 0],
	["/ItemList[4]/ArmorPart_RShoul", 15],
	["/ItemList[4]/ArmorPart_RShoul. ____type", 0],
	["/ItemList[4]/ArmorPart_RThigh", 3],
	["/ItemList[4]/ArmorPart_RThigh. ____type", 0],
	["/ItemList[4]/ArmorPart_Robe", 0],
	["/ItemList[4]/ArmorPart_Robe. ____type", 0],
	["/ItemList[4]/ArmorPart_Torso", 43],
	["/ItemList[4]/ArmorPart_Torso. ____type", 0],
	["/ItemList[4]/BaseItem", 16],
	["/ItemList[4]/BaseItem. ____type", 5],
	["/ItemList[4]/Charges", 0],
	["/ItemList[4]/Charges. ____type", 0],
	["/ItemList[4]/Cloth1Color", 2],
	["/ItemList[4]/Cloth1Color. ____type", 0],
	["/ItemList[4]/Cloth2Color", 3],
	["/ItemList[4]/Cloth2Color. ____type", 0],
	["/ItemList[4]/Cost", 15],
	["/ItemList[4]/Cost. ____type", 4],
	["/ItemList[4]/Cursed", 0],
	["/ItemList[4]/Cursed. ____type", 0],
	["/ItemList[4]/DescIdentified. ____string_ref", 4294967295],
	["/ItemList[4]/DescIdentified. ____type", 12],
	["/ItemList[4]/DescIdentifiedOv", ""],
	["/ItemList[4]/DescIdentifiedOv. ____type", 10],
	["/ItemList[4]/Description. ____string_ref", 4294967295],
	["/ItemList[4]/Description. ____type", 12],
	["/ItemList[4]/DescriptionOverr", ""],
	["/ItemList[4]/DescriptionOverr. ____type", 10],
	["/ItemList[4]/Dropable", 1],
	["/ItemList[4]/Dropable. ____type", 0],
	["/ItemList[4]/Identified", 1],
	["/ItemList[4]/Identified. ____type", 0],
	["/ItemList[4]/Leather1Color", 5],
	["/ItemList[4]/Leather1Color. ____type", 0],
	["/ItemList[4]/Leather2Color", 7],
	["/ItemList[4]/Leather2Color. ____type", 0],
	["/ItemList[4]/LocalizedName. ____string_ref", 12840],
	["/ItemList[4]/LocalizedName. ____type", 12],
	["/ItemList[4]/Metal1Color", 17],
	["/ItemList[4]/Metal1Color. ____type", 0],
	["/ItemList[4]/Metal2Color", 8],
	["/ItemList[4]/Metal2Color. ____type", 0],
	["/ItemList[4]/ObjectId", 587],
	["/ItemList[4]/ObjectId. ____type", 4],
	["/ItemList[4]/Pickpocketable", 1],
	["/ItemList[4]/Pickpocketable. ____type", 0],
	["/ItemList[4]/Plot", 0],
	["/ItemList[4]/Plot. ____type", 0],
	["/ItemList[4]/PropertiesList. ____type", 15],
	["/ItemList[4]/Repos_PosX", 1],
	["/ItemList[4]/Repos_PosX. ____type", 2],
	["/ItemList[4]/Repos_Posy", 0],
	["/ItemList[4]/Repos_Posy. ____type", 2],
	["/ItemList[4]/StackSize", 1],
	["/ItemList[4]/StackSize. ____type", 2],
	["/ItemList[4]/Stolen", 0],
	["/ItemList[4]/Stolen. ____type", 0],
	["/ItemList[4]/Tag", "NW_AARCL008"],
	["/ItemList[4]/Tag. ____type", 10],
	["/ItemList[4]/TemplateResRef", "nw_aarcl008"],
	["/ItemList[4]/TemplateResRef. ____type", 11],
	["/ItemList[4]/UArmorPart_Belt", 0],
	["/ItemList[4]/UArmorPart_Belt. ____type", 0],
	["/ItemList[4]/UArmorPart_LBice", 4],
	["/ItemList[4]/UArmorPart_LBice. ____type", 0],
	["/ItemList[4]/UArmorPart_LFArm", 16],
	["/ItemList[4]/UArmorPart_LFArm. ____type", 0],
	["/ItemList[4]/UArmorPart_LFoot", 4],
	["/ItemList[4]/UArmorPart_LFoot. ____type", 0],
	["/ItemList[4]/UArmorPart_LHand", 3],
	["/ItemList[4]/UArmorPart_LHand. ____type", 0],
	["/ItemList[4]/UArmorPart_LShin", 13],
	["/ItemList[4]/UArmorPart_LShin. ____type", 0],
	["/ItemList[4]/UArmorPart_LShou", 15],
	["/ItemList[4]/UArmorPart_LShou. ____type", 0],
	["/ItemList[4]/UArmorPart_LThig", 3],
	["/ItemList[4]/UArmorPart_LThig. ____type", 0],
	["/ItemList[4]/UArmorPart_Neck", 1],
	["/ItemList[4]/UArmorPart_Neck. ____type", 0],
	["/ItemList[4]/UArmorPart_Pelvi", 8],
	["/ItemList[4]/UArmorPart_Pelvi. ____type", 0],
	["/ItemList[4]/UArmorPart_RBice", 4],
	["/ItemList[4]/UArmorPart_RBice. ____type", 0],
	["/ItemList[4]/UArmorPart_RFArm", 16],
	["/ItemList[4]/UArmorPart_RFArm. ____type", 0],
	["/ItemList[4]/UArmorPart_RFoot", 4],
	["/ItemList[4]/UArmorPart_RFoot. ____type", 0],
	["/ItemList[4]/UArmorPart_RHand", 3],
	["/ItemList[4]/UArmorPart_RHand. ____type", 0],
	["/ItemList[4]/UArmorPart_RShin", 13],
	["/ItemList[4]/UArmorPart_RShin. ____type", 0],
	["/ItemList[4]/UArmorPart_RShou", 15],
	["/ItemList[4]/UArmorPart_RShou. ____type", 0],
	["/ItemList[4]/UArmorPart_RThig", 3],
	["/ItemList[4]/UArmorPart_RThig. ____type", 0],
	["/ItemList[4]/UArmorPart_Robe", 0],
	["/ItemList[4]/UArmorPart_Robe. ____type", 0],
	["/ItemList[4]/UArmorPart_Torso", 43],
	["/ItemList[4]/UArmorPart_Torso. ____type", 0],
	["/ItemList[4]/XOrientation", 1.0],
	["/ItemList[4]/XOrientation. ____type", 8],
	["/ItemList[4]/XPosition", 0.0],
	["/ItemList[4]/XPosition. ____type", 8],
	["/ItemList[4]/YOrientation", 0.0],
	["/ItemList[4]/YOrientation. ____type", 8],
	["/ItemList[4]/YPosition", 0.0],
	["/ItemList[4]/YPosition. ____type", 8],
	["/ItemList[4]/ZOrientation", 0.0],
	["/ItemList[4]/ZOrientation. ____type", 8],
	["/ItemList[4]/ZPosition", 0.0],
	["/ItemList[4]/ZPosition. ____type", 8],
	["/ItemList[5]/", "/ItemList[5]"],
	["/ItemList[5]/ ____struct_type", 0],
	["/ItemList[5]/AddCost", 0],
	["/ItemList[5]/AddCost. ____type", 4],
	["/ItemList[5]/BaseItem", 38],
	["/ItemList[5]/BaseItem. ____type", 5],
	["/ItemList[5]/Charges", 0],
	["/ItemList[5]/Charges. ____type", 0],
	["/ItemList[5]/Cost", 12],
	["/ItemList[5]/Cost. ____type", 4],
	["/ItemList[5]/Cursed", 0],
	["/ItemList[5]/Cursed. ____type", 0],
	["/ItemList[5]/DescIdentified. ____string_ref", 4294967295],
	["/ItemList[5]/DescIdentified. ____type", 12],
	["/ItemList[5]/DescIdentifiedOv", ""],
	["/ItemList[5]/DescIdentifiedOv. ____type", 10],
	["/ItemList[5]/Description. ____string_ref", 4294967295],
	["/ItemList[5]/Description. ____type", 12],
	["/ItemList[5]/DescriptionOverr", ""],
	["/ItemList[5]/DescriptionOverr. ____type", 10],
	["/ItemList[5]/Dropable", 1],
	["/ItemList[5]/Dropable. ____type", 0],
	["/ItemList[5]/Identified", 1],
	["/ItemList[5]/Identified. ____type", 0],
	["/ItemList[5]/LocalizedName. ____string_ref", 1532],
	["/ItemList[5]/LocalizedName. ____type", 12],
	["/ItemList[5]/ModelPart1", 11],
	["/ItemList[5]/ModelPart1. ____type", 0],
	["/ItemList[5]/ModelPart2", 11],
	["/ItemList[5]/ModelPart2. ____type", 0],
	["/ItemList[5]/ModelPart3", 11],
	["/ItemList[5]/ModelPart3. ____type", 0],
	["/ItemList[5]/ObjectId", 586],
	["/ItemList[5]/ObjectId. ____type", 4],
	["/ItemList[5]/Pickpocketable", 1],
	["/ItemList[5]/Pickpocketable. ____type", 0],
	["/ItemList[5]/Plot", 0],
	["/ItemList[5]/Plot. ____type", 0],
	["/ItemList[5]/PropertiesList. ____type", 15],
	["/ItemList[5]/Repos_PosX", 0],
	["/ItemList[5]/Repos_PosX. ____type", 2],
	["/ItemList[5]/Repos_Posy", 0],
	["/ItemList[5]/Repos_Posy. ____type", 2],
	["/ItemList[5]/StackSize", 1],
	["/ItemList[5]/StackSize. ____type", 2],
	["/ItemList[5]/Stolen", 0],
	["/ItemList[5]/Stolen. ____type", 0],
	["/ItemList[5]/Tag", "NW_WAXHN001"],
	["/ItemList[5]/Tag. ____type", 10],
	["/ItemList[5]/TemplateResRef", "nw_waxhn001"],
	["/ItemList[5]/TemplateResRef. ____type", 11],
	["/ItemList[5]/XOrientation", 1.0],
	["/ItemList[5]/XOrientation. ____type", 8],
	["/ItemList[5]/XPosition", 0.0],
	["/ItemList[5]/XPosition. ____type", 8],
	["/ItemList[5]/YOrientation", 0.0],
	["/ItemList[5]/YOrientation. ____type", 8],
	["/ItemList[5]/YPosition", 0.0],
	["/ItemList[5]/YPosition. ____type", 8],
	["/ItemList[5]/ZOrientation", 0.0],
	["/ItemList[5]/ZOrientation. ____type", 8],
	["/ItemList[5]/ZPosition", 0.0],
	["/ItemList[5]/ZPosition. ____type", 8],
	["/LastName. ____string_ref", 4294967295],
	["/LastName. ____type", 12],
	["/LastName/0", "Character"],
	["/LawfulChaotic", 15],
	["/LawfulChaotic. ____type", 0],
	["/Listening", 0],
	["/Listening. ____type", 0],
	["/Lootable", 0],
	["/Lootable. ____type", 0],
	["/LvlStatList. ____type", 15],
	["/LvlStatList[0]/", "/LvlStatList[0]"],
	["/LvlStatList[0]/ ____struct_type", 0],
	["/LvlStatList[0]/EpicLevel", 0],
	["/LvlStatList[0]/EpicLevel. ____type", 0],
	["/LvlStatList[0]/FeatList. ____type", 15],
	["/LvlStatList[0]/FeatList[0]/", "/LvlStatList[0]/FeatList[0]"],
	["/LvlStatList[0]/FeatList[0]/ ____struct_type", 0],
	["/LvlStatList[0]/FeatList[0]/Feat", 3],
	["/LvlStatList[0]/FeatList[0]/Feat. ____type", 2],
	["/LvlStatList[0]/FeatList[1]/", "/LvlStatList[0]/FeatList[1]"],
	["/LvlStatList[0]/FeatList[1]/ ____struct_type", 0],
	["/LvlStatList[0]/FeatList[1]/Feat", 4],
	["/LvlStatList[0]/FeatList[1]/Feat. ____type", 2],
	["/LvlStatList[0]/FeatList[2]/", "/LvlStatList[0]/FeatList[2]"],
	["/LvlStatList[0]/FeatList[2]/ ____struct_type", 0],
	["/LvlStatList[0]/FeatList[2]/Feat", 32],
	["/LvlStatList[0]/FeatList[2]/Feat. ____type", 2],
	["/LvlStatList[0]/FeatList[3]/", "/LvlStatList[0]/FeatList[3]"],
	["/LvlStatList[0]/FeatList[3]/ ____struct_type", 0],
	["/LvlStatList[0]/FeatList[3]/Feat", 45],
	["/LvlStatList[0]/FeatList[3]/Feat. ____type", 2],
	["/LvlStatList[0]/FeatList[4]/", "/LvlStatList[0]/FeatList[4]"],
	["/LvlStatList[0]/FeatList[4]/ ____struct_type", 0],
	["/LvlStatList[0]/FeatList[4]/Feat", 46],
	["/LvlStatList[0]/FeatList[4]/Feat. ____type", 2],
	["/LvlStatList[0]/FeatList[5]/", "/LvlStatList[0]/FeatList[5]"],
	["/LvlStatList[0]/FeatList[5]/ ____struct_type", 0],
	["/LvlStatList[0]/FeatList[5]/Feat", 194],
	["/LvlStatList[0]/FeatList[5]/Feat. ____type", 2],
	["/LvlStatList[0]/FeatList[6]/", "/LvlStatList[0]/FeatList[6]"],
	["/LvlStatList[0]/FeatList[6]/ ____struct_type", 0],
	["/LvlStatList[0]/FeatList[6]/Feat", 258],
	["/LvlStatList[0]/FeatList[6]/Feat. ____type", 2],
	["/LvlStatList[0]/FeatList[7]/", "/LvlStatList[0]/FeatList[7]"],
	["/LvlStatList[0]/FeatList[7]/ ____struct_type", 0],
	["/LvlStatList[0]/FeatList[7]/Feat", 293],
	["/LvlStatList[0]/FeatList[7]/Feat. ____type", 2],
	["/LvlStatList[0]/FeatList[8]/", "/LvlStatList[0]/FeatList[8]"],
	["/LvlStatList[0]/FeatList[8]/ ____struct_type", 0],
	["/LvlStatList[0]/FeatList[8]/Feat", 1089],
	["/LvlStatList[0]/FeatList[8]/Feat. ____type", 2],
	["/LvlStatList[0]/FeatList[9]/", "/LvlStatList[0]/FeatList[9]"],
	["/LvlStatList[0]/FeatList[9]/ ____struct_type", 0],
	["/LvlStatList[0]/FeatList[9]/Feat", 28],
	["/LvlStatList[0]/FeatList[9]/Feat. ____type", 2],
	["/LvlStatList[0]/FeatList[10]/", "/LvlStatList[0]/FeatList[10]"],
	["/LvlStatList[0]/FeatList[10]/ ____struct_type", 0],
	["/LvlStatList[0]/FeatList[10]/Feat", 111],
	["/LvlStatList[0]/FeatList[10]/Feat. ____type", 2],
	["/LvlStatList[0]/LvlStatClass", 0],
	["/LvlStatList[0]/LvlStatClass. ____type", 0],
	["/LvlStatList[0]/LvlStatHitDie", 12],
	["/LvlStatList[0]/LvlStatHitDie. ____type", 0],
	["/LvlStatList[0]/SkillList. ____type", 15],
	["/LvlStatList[0]/SkillList[0]/", "/LvlStatList[0]/SkillList[0]"],
	["/LvlStatList[0]/SkillList[0]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[0]/Rank", 0],
	["/LvlStatList[0]/SkillList[0]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[1]/", "/LvlStatList[0]/SkillList[1]"],
	["/LvlStatList[0]/SkillList[1]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[1]/Rank", 0],
	["/LvlStatList[0]/SkillList[1]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[2]/", "/LvlStatList[0]/SkillList[2]"],
	["/LvlStatList[0]/SkillList[2]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[2]/Rank", 0],
	["/LvlStatList[0]/SkillList[2]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[3]/", "/LvlStatList[0]/SkillList[3]"],
	["/LvlStatList[0]/SkillList[3]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[3]/Rank", 4],
	["/LvlStatList[0]/SkillList[3]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[4]/", "/LvlStatList[0]/SkillList[4]"],
	["/LvlStatList[0]/SkillList[4]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[4]/Rank", 0],
	["/LvlStatList[0]/SkillList[4]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[5]/", "/LvlStatList[0]/SkillList[5]"],
	["/LvlStatList[0]/SkillList[5]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[5]/Rank", 0],
	["/LvlStatList[0]/SkillList[5]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[6]/", "/LvlStatList[0]/SkillList[6]"],
	["/LvlStatList[0]/SkillList[6]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[6]/Rank", 4],
	["/LvlStatList[0]/SkillList[6]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[7]/", "/LvlStatList[0]/SkillList[7]"],
	["/LvlStatList[0]/SkillList[7]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[7]/Rank", 0],
	["/LvlStatList[0]/SkillList[7]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[8]/", "/LvlStatList[0]/SkillList[8]"],
	["/LvlStatList[0]/SkillList[8]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[8]/Rank", 0],
	["/LvlStatList[0]/SkillList[8]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[9]/", "/LvlStatList[0]/SkillList[9]"],
	["/LvlStatList[0]/SkillList[9]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[9]/Rank", 0],
	["/LvlStatList[0]/SkillList[9]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[10]/", "/LvlStatList[0]/SkillList[10]"],
	["/LvlStatList[0]/SkillList[10]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[10]/Rank", 4],
	["/LvlStatList[0]/SkillList[10]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[11]/", "/LvlStatList[0]/SkillList[11]"],
	["/LvlStatList[0]/SkillList[11]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[11]/Rank", 0],
	["/LvlStatList[0]/SkillList[11]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[12]/", "/LvlStatList[0]/SkillList[12]"],
	["/LvlStatList[0]/SkillList[12]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[12]/Rank", 0],
	["/LvlStatList[0]/SkillList[12]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[13]/", "/LvlStatList[0]/SkillList[13]"],
	["/LvlStatList[0]/SkillList[13]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[13]/Rank", 0],
	["/LvlStatList[0]/SkillList[13]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[14]/", "/LvlStatList[0]/SkillList[14]"],
	["/LvlStatList[0]/SkillList[14]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[14]/Rank", 0],
	["/LvlStatList[0]/SkillList[14]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[15]/", "/LvlStatList[0]/SkillList[15]"],
	["/LvlStatList[0]/SkillList[15]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[15]/Rank", 0],
	["/LvlStatList[0]/SkillList[15]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[16]/", "/LvlStatList[0]/SkillList[16]"],
	["/LvlStatList[0]/SkillList[16]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[16]/Rank", 0],
	["/LvlStatList[0]/SkillList[16]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[17]/", "/LvlStatList[0]/SkillList[17]"],
	["/LvlStatList[0]/SkillList[17]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[17]/Rank", 2],
	["/LvlStatList[0]/SkillList[17]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[18]/", "/LvlStatList[0]/SkillList[18]"],
	["/LvlStatList[0]/SkillList[18]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[18]/Rank", 4],
	["/LvlStatList[0]/SkillList[18]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[19]/", "/LvlStatList[0]/SkillList[19]"],
	["/LvlStatList[0]/SkillList[19]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[19]/Rank", 0],
	["/LvlStatList[0]/SkillList[19]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[20]/", "/LvlStatList[0]/SkillList[20]"],
	["/LvlStatList[0]/SkillList[20]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[20]/Rank", 0],
	["/LvlStatList[0]/SkillList[20]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[21]/", "/LvlStatList[0]/SkillList[21]"],
	["/LvlStatList[0]/SkillList[21]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[21]/Rank", 0],
	["/LvlStatList[0]/SkillList[21]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[22]/", "/LvlStatList[0]/SkillList[22]"],
	["/LvlStatList[0]/SkillList[22]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[22]/Rank", 0],
	["/LvlStatList[0]/SkillList[22]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[23]/", "/LvlStatList[0]/SkillList[23]"],
	["/LvlStatList[0]/SkillList[23]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[23]/Rank", 0],
	["/LvlStatList[0]/SkillList[23]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[24]/", "/LvlStatList[0]/SkillList[24]"],
	["/LvlStatList[0]/SkillList[24]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[24]/Rank", 0],
	["/LvlStatList[0]/SkillList[24]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[25]/", "/LvlStatList[0]/SkillList[25]"],
	["/LvlStatList[0]/SkillList[25]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[25]/Rank", 0],
	["/LvlStatList[0]/SkillList[25]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[26]/", "/LvlStatList[0]/SkillList[26]"],
	["/LvlStatList[0]/SkillList[26]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[26]/Rank", 0],
	["/LvlStatList[0]/SkillList[26]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillList[27]/", "/LvlStatList[0]/SkillList[27]"],
	["/LvlStatList[0]/SkillList[27]/ ____struct_type", 0],
	["/LvlStatList[0]/SkillList[27]/Rank", 0],
	["/LvlStatList[0]/SkillList[27]/Rank. ____type", 0],
	["/LvlStatList[0]/SkillPoints", 0],
	["/LvlStatList[0]/SkillPoints. ____type", 2],
	["/MClassLevUpIn", 0],
	["/MClassLevUpIn. ____type", 0],
	["/MasterID", 2130706432],
	["/MasterID. ____type", 4],
	["/MaxHitPoints", 14],
	["/MaxHitPoints. ____type", 3],
	["/MovementRate", 0],
	["/MovementRate. ____type", 0],
	["/NaturalAC", 0],
	["/NaturalAC. ____type", 0],
	["/NoPermDeath", 0],
	["/NoPermDeath. ____type", 0],
	["/OverrideBAB", 0],
	["/OverrideBAB. ____type", 0],
	["/PM_IsPolymorphed", 0],
	["/PM_IsPolymorphed. ____type", 0],
	["/PerceptionList. ____type", 15],
	["/PerceptionList[0]/", "/PerceptionList[0]"],
	["/PerceptionList[0]/ ____struct_type", 0],
	["/PerceptionList[0]/ObjectId", 2147483647],
	["/PerceptionList[0]/ObjectId. ____type", 4],
	["/PerceptionList[0]/PerceptionData", 3],
	["/PerceptionList[0]/PerceptionData. ____type", 0],
	["/PerceptionList[1]/", "/PerceptionList[1]"],
	["/PerceptionList[1]/ ____struct_type", 0],
	["/PerceptionList[1]/ObjectId", 175],
	["/PerceptionList[1]/ObjectId. ____type", 4],
	["/PerceptionList[1]/PerceptionData", 3],
	["/PerceptionList[1]/PerceptionData. ____type", 0],
	["/PerceptionList[2]/", "/PerceptionList[2]"],
	["/PerceptionList[2]/ ____struct_type", 0],
	["/PerceptionList[2]/ObjectId", 149],
	["/PerceptionList[2]/ObjectId. ____type", 4],
	["/PerceptionList[2]/PerceptionData", 3],
	["/PerceptionList[2]/PerceptionData. ____type", 0],
	["/PerceptionList[3]/", "/PerceptionList[3]"],
	["/PerceptionList[3]/ ____struct_type", 0],
	["/PerceptionList[3]/ObjectId", 140],
	["/PerceptionList[3]/ObjectId. ____type", 4],
	["/PerceptionList[3]/PerceptionData", 3],
	["/PerceptionList[3]/PerceptionData. ____type", 0],
	["/PerceptionList[4]/", "/PerceptionList[4]"],
	["/PerceptionList[4]/ ____struct_type", 0],
	["/PerceptionList[4]/ObjectId", 123],
	["/PerceptionList[4]/ObjectId. ____type", 4],
	["/PerceptionList[4]/PerceptionData", 3],
	["/PerceptionList[4]/PerceptionData. ____type", 0],
	["/PerceptionList[5]/", "/PerceptionList[5]"],
	["/PerceptionList[5]/ ____struct_type", 0],
	["/PerceptionList[5]/ObjectId", 116],
	["/PerceptionList[5]/ObjectId. ____type", 4],
	["/PerceptionList[5]/PerceptionData", 3],
	["/PerceptionList[5]/PerceptionData. ____type", 0],
	["/PerceptionList[6]/", "/PerceptionList[6]"],
	["/PerceptionList[6]/ ____struct_type", 0],
	["/PerceptionList[6]/ObjectId", 109],
	["/PerceptionList[6]/ObjectId. ____type", 4],
	["/PerceptionList[6]/PerceptionData", 3],
	["/PerceptionList[6]/PerceptionData. ____type", 0],
	["/PerceptionList[7]/", "/PerceptionList[7]"],
	["/PerceptionList[7]/ ____struct_type", 0],
	["/PerceptionList[7]/ObjectId", 166],
	["/PerceptionList[7]/ObjectId. ____type", 4],
	["/PerceptionList[7]/PerceptionData", 3],
	["/PerceptionList[7]/PerceptionData. ____type", 0],
	["/PerceptionList[8]/", "/PerceptionList[8]"],
	["/PerceptionList[8]/ ____struct_type", 0],
	["/PerceptionList[8]/ObjectId", 157],
	["/PerceptionList[8]/ObjectId. ____type", 4],
	["/PerceptionList[8]/PerceptionData", 3],
	["/PerceptionList[8]/PerceptionData. ____type", 0],
	["/PerceptionList[9]/", "/PerceptionList[9]"],
	["/PerceptionList[9]/ ____struct_type", 0],
	["/PerceptionList[9]/ObjectId", 131],
	["/PerceptionList[9]/ObjectId. ____type", 4],
	["/PerceptionList[9]/PerceptionData", 3],
	["/PerceptionList[9]/PerceptionData. ____type", 0],
	["/Phenotype", 0],
	["/Phenotype. ____type", 5],
	["/Plot", 0],
	["/Plot. ____type", 0],
	["/Portrait", "po_hu_m_02_"],
	["/Portrait. ____type", 11],
	["/PregameCurrent", 14],
	["/PregameCurrent. ____type", 3],
	["/QBList. ____type", 15],
	["/QBList[0]/", "/QBList[0]"],
	["/QBList[0]/ ____struct_type", 0],
	["/QBList[0]/QBINTParam1", 1],
	["/QBList[0]/QBINTParam1. ____type", 5],
	["/QBList[0]/QBObjectType", 10],
	["/QBList[0]/QBObjectType. ____type", 0],
	["/QBList[1]/", "/QBList[1]"],
	["/QBList[1]/ ____struct_type", 0],
	["/QBList[1]/QBINTParam1", 0],
	["/QBList[1]/QBINTParam1. ____type", 5],
	["/QBList[1]/QBObjectType", 10],
	["/QBList[1]/QBObjectType. ____type", 0],
	["/QBList[2]/", "/QBList[2]"],
	["/QBList[2]/ ____struct_type", 0],
	["/QBList[2]/QBCastPropIndex", 255],
	["/QBList[2]/QBCastPropIndex. ____type", 0],
	["/QBList[2]/QBCastSubPropIdx", 255],
	["/QBList[2]/QBCastSubPropIdx. ____type", 0],
	["/QBList[2]/QBContReposX", 255],
	["/QBList[2]/QBContReposX. ____type", 0],
	["/QBList[2]/QBContReposY", 255],
	["/QBList[2]/QBContReposY. ____type", 0],
	["/QBList[2]/QBItemInvSlot", 4294967295],
	["/QBList[2]/QBItemInvSlot. ____type", 4],
	["/QBList[2]/QBItemReposX", 0],
	["/QBList[2]/QBItemReposX. ____type", 0],
	["/QBList[2]/QBItemReposY", 0],
	["/QBList[2]/QBItemReposY. ____type", 0],
	["/QBList[2]/QBObjectType", 1],
	["/QBList[2]/QBObjectType. ____type", 0],
	["/QBList[3]/", "/QBList[3]"],
	["/QBList[3]/ ____struct_type", 0],
	["/QBList[3]/QBCastPropIndex", 255],
	["/QBList[3]/QBCastPropIndex. ____type", 0],
	["/QBList[3]/QBCastSubPropIdx", 255],
	["/QBList[3]/QBCastSubPropIdx. ____type", 0],
	["/QBList[3]/QBContReposX", 255],
	["/QBList[3]/QBContReposX. ____type", 0],
	["/QBList[3]/QBContReposY", 255],
	["/QBList[3]/QBContReposY. ____type", 0],
	["/QBList[3]/QBItemInvSlot", 4294967295],
	["/QBList[3]/QBItemInvSlot. ____type", 4],
	["/QBList[3]/QBItemReposX", 6],
	["/QBList[3]/QBItemReposX. ____type", 0],
	["/QBList[3]/QBItemReposY", 0],
	["/QBList[3]/QBItemReposY. ____type", 0],
	["/QBList[3]/QBObjectType", 1],
	["/QBList[3]/QBObjectType. ____type", 0],
	["/QBList[4]/", "/QBList[4]"],
	["/QBList[4]/ ____struct_type", 0],
	["/QBList[4]/QBINTParam1", 293],
	["/QBList[4]/QBINTParam1. ____type", 5],
	["/QBList[4]/QBObjectType", 4],
	["/QBList[4]/QBObjectType. ____type", 0],
	["/QBList[5]/", "/QBList[5]"],
	["/QBList[5]/ ____struct_type", 0],
	["/QBList[5]/QBINTParam1", 28],
	["/QBList[5]/QBINTParam1. ____type", 5],
	["/QBList[5]/QBObjectType", 4],
	["/QBList[5]/QBObjectType. ____type", 0],
	["/QBList[6]/", "/QBList[6]"],
	["/QBList[6]/ ____struct_type", 0],
	["/QBList[6]/QBObjectType", 0],
	["/QBList[6]/QBObjectType. ____type", 0],
	["/QBList[7]/", "/QBList[7]"],
	["/QBList[7]/ ____struct_type", 0],
	["/QBList[7]/QBObjectType", 0],
	["/QBList[7]/QBObjectType. ____type", 0],
	["/QBList[8]/", "/QBList[8]"],
	["/QBList[8]/ ____struct_type", 0],
	["/QBList[8]/QBObjectType", 0],
	["/QBList[8]/QBObjectType. ____type", 0],
	["/QBList[9]/", "/QBList[9]"],
	["/QBList[9]/ ____struct_type", 0],
	["/QBList[9]/QBObjectType", 0],
	["/QBList[9]/QBObjectType. ____type", 0],
	["/QBList[10]/", "/QBList[10]"],
	["/QBList[10]/ ____struct_type", 0],
	["/QBList[10]/QBObjectType", 0],
	["/QBList[10]/QBObjectType. ____type", 0],
	["/QBList[11]/", "/QBList[11]"],
	["/QBList[11]/ ____struct_type", 0],
	["/QBList[11]/QBObjectType", 0],
	["/QBList[11]/QBObjectType. ____type", 0],
	["/QBList[12]/", "/QBList[12]"],
	["/QBList[12]/ ____struct_type", 0],
	["/QBList[12]/QBObjectType", 0],
	["/QBList[12]/QBObjectType. ____type", 0],
	["/QBList[13]/", "/QBList[13]"],
	["/QBList[13]/ ____struct_type", 0],
	["/QBList[13]/QBObjectType", 0],
	["/QBList[13]/QBObjectType. ____type", 0],
	["/QBList[14]/", "/QBList[14]"],
	["/QBList[14]/ ____struct_type", 0],
	["/QBList[14]/QBObjectType", 0],
	["/QBList[14]/QBObjectType. ____type", 0],
	["/QBList[15]/", "/QBList[15]"],
	["/QBList[15]/ ____struct_type", 0],
	["/QBList[15]/QBObjectType", 0],
	["/QBList[15]/QBObjectType. ____type", 0],
	["/QBList[16]/", "/QBList[16]"],
	["/QBList[16]/ ____struct_type", 0],
	["/QBList[16]/QBObjectType", 0],
	["/QBList[16]/QBObjectType. ____type", 0],
	["/QBList[17]/", "/QBList[17]"],
	["/QBList[17]/ ____struct_type", 0],
	["/QBList[17]/QBObjectType", 0],
	["/QBList[17]/QBObjectType. ____type", 0],
	["/QBList[18]/", "/QBList[18]"],
	["/QBList[18]/ ____struct_type", 0],
	["/QBList[18]/QBObjectType", 0],
	["/QBList[18]/QBObjectType. ____type", 0],
	["/QBList[19]/", "/QBList[19]"],
	["/QBList[19]/ ____struct_type", 0],
	["/QBList[19]/QBObjectType", 0],
	["/QBList[19]/QBObjectType. ____type", 0],
	["/QBList[20]/", "/QBList[20]"],
	["/QBList[20]/ ____struct_type", 0],
	["/QBList[20]/QBObjectType", 0],
	["/QBList[20]/QBObjectType. ____type", 0],
	["/QBList[21]/", "/QBList[21]"],
	["/QBList[21]/ ____struct_type", 0],
	["/QBList[21]/QBObjectType", 0],
	["/QBList[21]/QBObjectType. ____type", 0],
	["/QBList[22]/", "/QBList[22]"],
	["/QBList[22]/ ____struct_type", 0],
	["/QBList[22]/QBObjectType", 0],
	["/QBList[22]/QBObjectType. ____type", 0],
	["/QBList[23]/", "/QBList[23]"],
	["/QBList[23]/ ____struct_type", 0],
	["/QBList[23]/QBObjectType", 0],
	["/QBList[23]/QBObjectType. ____type", 0],
	["/QBList[24]/", "/QBList[24]"],
	["/QBList[24]/ ____struct_type", 0],
	["/QBList[24]/QBObjectType", 0],
	["/QBList[24]/QBObjectType. ____type", 0],
	["/QBList[25]/", "/QBList[25]"],
	["/QBList[25]/ ____struct_type", 0],
	["/QBList[25]/QBObjectType", 0],
	["/QBList[25]/QBObjectType. ____type", 0],
	["/QBList[26]/", "/QBList[26]"],
	["/QBList[26]/ ____struct_type", 0],
	["/QBList[26]/QBObjectType", 0],
	["/QBList[26]/QBObjectType. ____type", 0],
	["/QBList[27]/", "/QBList[27]"],
	["/QBList[27]/ ____struct_type", 0],
	["/QBList[27]/QBObjectType", 0],
	["/QBList[27]/QBObjectType. ____type", 0],
	["/QBList[28]/", "/QBList[28]"],
	["/QBList[28]/ ____struct_type", 0],
	["/QBList[28]/QBObjectType", 0],
	["/QBList[28]/QBObjectType. ____type", 0],
	["/QBList[29]/", "/QBList[29]"],
	["/QBList[29]/ ____struct_type", 0],
	["/QBList[29]/QBObjectType", 0],
	["/QBList[29]/QBObjectType. ____type", 0],
	["/QBList[30]/", "/QBList[30]"],
	["/QBList[30]/ ____struct_type", 0],
	["/QBList[30]/QBObjectType", 0],
	["/QBList[30]/QBObjectType. ____type", 0],
	["/QBList[31]/", "/QBList[31]"],
	["/QBList[31]/ ____struct_type", 0],
	["/QBList[31]/QBObjectType", 0],
	["/QBList[31]/QBObjectType. ____type", 0],
	["/QBList[32]/", "/QBList[32]"],
	["/QBList[32]/ ____struct_type", 0],
	["/QBList[32]/QBObjectType", 0],
	["/QBList[32]/QBObjectType. ____type", 0],
	["/QBList[33]/", "/QBList[33]"],
	["/QBList[33]/ ____struct_type", 0],
	["/QBList[33]/QBObjectType", 0],
	["/QBList[33]/QBObjectType. ____type", 0],
	["/QBList[34]/", "/QBList[34]"],
	["/QBList[34]/ ____struct_type", 0],
	["/QBList[34]/QBObjectType", 0],
	["/QBList[34]/QBObjectType. ____type", 0],
	["/QBList[35]/", "/QBList[35]"],
	["/QBList[35]/ ____struct_type", 0],
	["/QBList[35]/QBObjectType", 0],
	["/QBList[35]/QBObjectType. ____type", 0],
	["/Race", 6],
	["/Race. ____type", 0],
	["/RefSaveThrow", 2],
	["/RefSaveThrow. ____type", 1],
	["/ScriptAttacked", "default"],
	["/ScriptAttacked. ____type", 11],
	["/ScriptDamaged", "default"],
	["/ScriptDamaged. ____type", 11],
	["/ScriptDeath", "default"],
	["/ScriptDeath. ____type", 11],
	["/ScriptDialogue", "default"],
	["/ScriptDialogue. ____type", 11],
	["/ScriptDisturbed", "default"],
	["/ScriptDisturbed. ____type", 11],
	["/ScriptEndRound", "default"],
	["/ScriptEndRound. ____type", 11],
	["/ScriptHeartbeat", "default"],
	["/ScriptHeartbeat. ____type", 11],
	["/ScriptOnBlocked", "default"],
	["/ScriptOnBlocked. ____type", 11],
	["/ScriptOnNotice", "default"],
	["/ScriptOnNotice. ____type", 11],
	["/ScriptRested", "default"],
	["/ScriptRested. ____type", 11],
	["/ScriptSpawn", "default"],
	["/ScriptSpawn. ____type", 11],
	["/ScriptSpellAt", "default"],
	["/ScriptSpellAt. ____type", 11],
	["/ScriptUserDefine", "default"],
	["/ScriptUserDefine. ____type", 11],
	["/SitObject", 2130706432],
	["/SitObject. ____type", 4],
	["/SkillList. ____type", 15],
	["/SkillList[0]/", "/SkillList[0]"],
	["/SkillList[0]/ ____struct_type", 0],
	["/SkillList[0]/Rank", 0],
	["/SkillList[0]/Rank. ____type", 0],
	["/SkillList[1]/", "/SkillList[1]"],
	["/SkillList[1]/ ____struct_type", 0],
	["/SkillList[1]/Rank", 0],
	["/SkillList[1]/Rank. ____type", 0],
	["/SkillList[2]/", "/SkillList[2]"],
	["/SkillList[2]/ ____struct_type", 0],
	["/SkillList[2]/Rank", 0],
	["/SkillList[2]/Rank. ____type", 0],
	["/SkillList[3]/", "/SkillList[3]"],
	["/SkillList[3]/ ____struct_type", 0],
	["/SkillList[3]/Rank", 4],
	["/SkillList[3]/Rank. ____type", 0],
	["/SkillList[4]/", "/SkillList[4]"],
	["/SkillList[4]/ ____struct_type", 0],
	["/SkillList[4]/Rank", 0],
	["/SkillList[4]/Rank. ____type", 0],
	["/SkillList[5]/", "/SkillList[5]"],
	["/SkillList[5]/ ____struct_type", 0],
	["/SkillList[5]/Rank", 0],
	["/SkillList[5]/Rank. ____type", 0],
	["/SkillList[6]/", "/SkillList[6]"],
	["/SkillList[6]/ ____struct_type", 0],
	["/SkillList[6]/Rank", 4],
	["/SkillList[6]/Rank. ____type", 0],
	["/SkillList[7]/", "/SkillList[7]"],
	["/SkillList[7]/ ____struct_type", 0],
	["/SkillList[7]/Rank", 0],
	["/SkillList[7]/Rank. ____type", 0],
	["/SkillList[8]/", "/SkillList[8]"],
	["/SkillList[8]/ ____struct_type", 0],
	["/SkillList[8]/Rank", 0],
	["/SkillList[8]/Rank. ____type", 0],
	["/SkillList[9]/", "/SkillList[9]"],
	["/SkillList[9]/ ____struct_type", 0],
	["/SkillList[9]/Rank", 0],
	["/SkillList[9]/Rank. ____type", 0],
	["/SkillList[10]/", "/SkillList[10]"],
	["/SkillList[10]/ ____struct_type", 0],
	["/SkillList[10]/Rank", 4],
	["/SkillList[10]/Rank. ____type", 0],
	["/SkillList[11]/", "/SkillList[11]"],
	["/SkillList[11]/ ____struct_type", 0],
	["/SkillList[11]/Rank", 0],
	["/SkillList[11]/Rank. ____type", 0],
	["/SkillList[12]/", "/SkillList[12]"],
	["/SkillList[12]/ ____struct_type", 0],
	["/SkillList[12]/Rank", 0],
	["/SkillList[12]/Rank. ____type", 0],
	["/SkillList[13]/", "/SkillList[13]"],
	["/SkillList[13]/ ____struct_type", 0],
	["/SkillList[13]/Rank", 0],
	["/SkillList[13]/Rank. ____type", 0],
	["/SkillList[14]/", "/SkillList[14]"],
	["/SkillList[14]/ ____struct_type", 0],
	["/SkillList[14]/Rank", 0],
	["/SkillList[14]/Rank. ____type", 0],
	["/SkillList[15]/", "/SkillList[15]"],
	["/SkillList[15]/ ____struct_type", 0],
	["/SkillList[15]/Rank", 0],
	["/SkillList[15]/Rank. ____type", 0],
	["/SkillList[16]/", "/SkillList[16]"],
	["/SkillList[16]/ ____struct_type", 0],
	["/SkillList[16]/Rank", 0],
	["/SkillList[16]/Rank. ____type", 0],
	["/SkillList[17]/", "/SkillList[17]"],
	["/SkillList[17]/ ____struct_type", 0],
	["/SkillList[17]/Rank", 2],
	["/SkillList[17]/Rank. ____type", 0],
	["/SkillList[18]/", "/SkillList[18]"],
	["/SkillList[18]/ ____struct_type", 0],
	["/SkillList[18]/Rank", 4],
	["/SkillList[18]/Rank. ____type", 0],
	["/SkillList[19]/", "/SkillList[19]"],
	["/SkillList[19]/ ____struct_type", 0],
	["/SkillList[19]/Rank", 0],
	["/SkillList[19]/Rank. ____type", 0],
	["/SkillList[20]/", "/SkillList[20]"],
	["/SkillList[20]/ ____struct_type", 0],
	["/SkillList[20]/Rank", 0],
	["/SkillList[20]/Rank. ____type", 0],
	["/SkillList[21]/", "/SkillList[21]"],
	["/SkillList[21]/ ____struct_type", 0],
	["/SkillList[21]/Rank", 0],
	["/SkillList[21]/Rank. ____type", 0],
	["/SkillList[22]/", "/SkillList[22]"],
	["/SkillList[22]/ ____struct_type", 0],
	["/SkillList[22]/Rank", 0],
	["/SkillList[22]/Rank. ____type", 0],
	["/SkillList[23]/", "/SkillList[23]"],
	["/SkillList[23]/ ____struct_type", 0],
	["/SkillList[23]/Rank", 0],
	["/SkillList[23]/Rank. ____type", 0],
	["/SkillList[24]/", "/SkillList[24]"],
	["/SkillList[24]/ ____struct_type", 0],
	["/SkillList[24]/Rank", 0],
	["/SkillList[24]/Rank. ____type", 0],
	["/SkillList[25]/", "/SkillList[25]"],
	["/SkillList[25]/ ____struct_type", 0],
	["/SkillList[25]/Rank", 0],
	["/SkillList[25]/Rank. ____type", 0],
	["/SkillList[26]/", "/SkillList[26]"],
	["/SkillList[26]/ ____struct_type", 0],
	["/SkillList[26]/Rank", 0],
	["/SkillList[26]/Rank. ____type", 0],
	["/SkillList[27]/", "/SkillList[27]"],
	["/SkillList[27]/ ____struct_type", 0],
	["/SkillList[27]/Rank", 0],
	["/SkillList[27]/Rank. ____type", 0],
	["/SkillPoints", 0],
	["/SkillPoints. ____type", 2],
	["/SoundSetFile", 216],
	["/SoundSetFile. ____type", 2],
	["/StartingPackage", 0],
	["/StartingPackage. ____type", 0],
	["/StealthMode", 0],
	["/StealthMode. ____type", 0],
	["/Str", 16],
	["/Str. ____type", 0],
	["/Subrace", ""],
	["/Subrace. ____type", 10],
	["/Tag", ""],
	["/Tag. ____type", 10],
	["/Tail_New", 14],
	["/Tail_New. ____type", 4],
	["/TemplateResRef", ""],
	["/TemplateResRef. ____type", 11],
	["/WillSaveThrow", 0],
	["/WillSaveThrow. ____type", 1],
	["/Wings_New", 0],
	["/Wings_New. ____type", 4],
	["/Wis", 10],
	["/Wis. ____type", 0],
	["/XOrientation", -0.931925296783447],
	["/XOrientation. ____type", 8],
	["/XPosition", 9.91707420349121],
	["/XPosition. ____type", 8],
	["/YOrientation", -0.362650394439697],
	["/YOrientation. ____type", 8],
	["/YPosition", 4.97920179367065],
	["/YPosition. ____type", 8],
	["/ZOrientation", 0.0],
	["/ZOrientation. ____type", 8],
	["/ZPosition", 0.000121737910376396],
	["/ZPosition. ____type", 8],
	["/fortbonus", 0],
	["/fortbonus. ____type", 3],
	["/refbonus", 0],
	["/refbonus. ____type", 3],
	["/willbonus", 0],
	["/willbonus. ____type", 3]
].freeze
